import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {PrismaPg} from '@prisma/adapter-pg';
import {PrismaClient} from '../../src/generated/prisma/client';
import {sign} from '../../src/lib/scaleplus-automations/protocol';
import {handleAutomation} from '../../src/lib/scaleplus-automations/handler';
import {drainOutbox} from '../../src/lib/scaleplus-automations/delivery';
import {automationDatabaseConfig} from '../../src/lib/scaleplus-automations/database-config';
const url=process.env.AUTOMATION_TEST_DATABASE_URL;
test('LeadFinder actual Prisma/PostgreSQL and signed HTTP lifecycle',{skip:!url},async t=>{
 const parsed=new URL(url!);assert.equal(parsed.hostname,'localhost');assert.equal(parsed.pathname,'/leadfinder_automation_test');
 process.env.DATABASE_URL=url;process.env.SCALEPLUS_AUTOMATIONS_ENABLED='true';process.env.SCALEPLUS_AUTOMATION_SERVICE_SECRET='synthetic-service';process.env.PIPELEADSFINDER_AUTOMATION_WEBHOOK_SECRET='synthetic-webhook';
 const pool=new Pool(automationDatabaseConfig(url,'test'));const db=new PrismaClient({adapter:new PrismaPg(pool,{schema:'pipeleads'})});
 const received:Record<string,unknown>[]=[];let code=200,ack:unknown={data:{accepted:true,mapped:true}},redirects=0;
 const server=createServer(async(req,res)=>{try{const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));const raw=Buffer.concat(chunks);if(req.url==='/callback'){assert.equal(req.headers['x-scaleplus-signature'],sign('synthetic-webhook',String(req.headers['x-scaleplus-timestamp']),raw));received.push(JSON.parse(raw.toString()));res.statusCode=code;if(code===307)res.setHeader('location','/redirect');res.end(JSON.stringify(ack));return;}if(req.url==='/redirect'){redirects++;res.end('{}');return;}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);const response=await handleAutomation(new Request(`http://localhost${req.url}`,{method:req.method,headers,body:raw}),req.url!.split('/automations/')[1],()=>pool);res.statusCode=response.status;res.end(await response.text());}catch(error){res.statusCode=500;res.end(String(error));}});
 server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const base=`http://127.0.0.1:${address.port}`;process.env.PIPELEADSFINDER_AUTOMATION_WEBHOOK_URL=`${base}/callback`;
 const identity={subject:'subject-a',tenantId:'destination-a',scopeId:'list-a',bindingId:'binding-a'};
 async function call(endpoint:string,data:Record<string,unknown>={},requestId=randomUUID()){const body=JSON.stringify({...identity,...data,requestId}),ts=Math.floor(Date.now()/1000).toString();return fetch(`${base}/api/internal/scaleplus/automations/${endpoint}`,{method:'POST',headers:{'content-type':'application/json','x-scaleplus-app':'mailbaser','x-scaleplus-request-id':requestId,'x-scaleplus-timestamp':ts,'x-scaleplus-signature':sign('synthetic-service',ts,body)},body});}
 async function addLead(id='lead-a',email:string|null='prospect@example.test',owner='owner-a',list='list-a'){await db.lead.create({data:{id,userId:owner,email,fullName:'Synthetic prospect',sourceType:'PEOPLE',rawData:{private:'not exported'}}});return db.leadListEntry.create({data:{id:`entry-${id}`,listId:list,leadId:id}});}
 async function fixture(two=false){await pool.query('TRUNCATE scaleplus_automation_outbox,scaleplus_automation_bindings,scaleplus_automation_requests,scaleplus_automation_actions,"User" CASCADE');await db.user.createMany({data:[{id:'owner-a',keycloakSubId:'subject-a',email:'owner@example.test'},{id:'owner-b',keycloakSubId:'subject-b',email:'other@example.test'}]});await db.leadList.createMany({data:[{id:'list-a',userId:'owner-a',name:'Owned list',type:'PEOPLE'},{id:'list-b',userId:'owner-b',name:'Foreign list',type:'PEOPLE'},{id:'archived',userId:'owner-a',name:'Archived',type:'PEOPLE',status:'ARCHIVED'}]});await db.customLabel.createMany({data:[{id:'label-a',userId:'owner-a',name:'Owned label'},{id:'label-b',userId:'owner-b',name:'Foreign label'}]});assert.equal((await call('bindings')).status,200);if(two)assert.equal((await call('bindings',{bindingId:'binding-b',tenantId:'destination-b'})).status,200);received.length=0;code=200;ack={data:{accepted:true,mapped:true}};return addLead();}
 const rows=async()=>(await pool.query('SELECT * FROM scaleplus_automation_outbox ORDER BY created_at,event_id')).rows;
 const clear=()=>pool.query('DELETE FROM scaleplus_automation_outbox');
 const action=(extra:Record<string,unknown>={})=>({operation:'apply_existing_label',idempotencyKey:'apply-once',contact:{email:'prospect@example.test'},config:{labelId:'label-a'},...extra});
 try{
  const migration=readFileSync(new URL('../../prisma/migrations/add-scaleplus-automations.sql',import.meta.url),'utf8');await pool.query(migration);await pool.query(migration);
  await t.test('native entry insertion emits per-binding neutral prospect IDs and strict UTC timestamp',async()=>{await fixture(true);const out=await rows();assert.equal(out.length,2);assert.notEqual(out[0].event_id,out[1].event_id);assert.equal(out[0].source_event_id,out[1].source_event_id);assert.equal(out[0].payload.data.identityKind,'prospect');assert.match(out[0].payload.occurredAt,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);assert.equal(JSON.stringify(out).includes('not exported'),false);assert.equal('consentGiven' in out[0].payload.data,false);await Promise.all([drainOutbox(pool),drainOutbox(pool)]);assert.equal(received.length,2);assert.ok((await rows()).every(r=>r.delivered_at));});
  await t.test('native search persistence captures saved entries without calling search providers',async()=>{await fixture();await clear();const {persistSearchResults}=await import('../../src/services/search-persistence');const {prisma}=await import('../../src/lib/prisma');try{await persistSearchResults({searchId:'unused-no-search-job',userId:'owner-a',listId:'list-a',searchType:'PEOPLE',results:[{email:'native@example.test',fullName:'Native fixture'}],markCompleted:false});assert.equal((await rows()).length,1);assert.equal((await rows())[0].payload.contact.email,'native@example.test');await persistSearchResults({searchId:'unused-no-search-job',userId:'owner-a',listId:'list-a',searchType:'PEOPLE',results:[{email:'native@example.test'}],duplicatePolicy:'RETURN_ALL',markCompleted:false});assert.equal((await rows()).length,1);}finally{await prisma.$disconnect();}});
  await t.test('native single and bulk label insertion captures real assignments, not duplicate no-ops',async()=>{await fixture();await clear();await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-a'}});assert.equal((await rows())[0].event_key,'lead_label_added');await db.leadEntryLabel.createMany({data:[{entryId:'entry-lead-a',labelId:'label-a'}],skipDuplicates:true});assert.equal((await rows()).length,1);});
  await t.test('actual Prisma transaction rolls back entry and outbox together',async()=>{await fixture();await clear();await assert.rejects(db.$transaction(async tx=>{await tx.lead.create({data:{id:'rolled-lead',userId:'owner-a',email:'rollback@example.test',sourceType:'PEOPLE'}});await tx.leadListEntry.create({data:{id:'rollback',listId:'list-a',leadId:'rolled-lead'}});const captured=await tx.$queryRaw<Array<{count:bigint}>>`SELECT count(*) FROM scaleplus_automation_outbox`;assert.equal(Number(captured[0].count),1);throw new Error('rollback');}));assert.equal((await rows()).length,0);assert.equal(await db.leadListEntry.count({where:{id:'rollback'}}),0);});
  await t.test('catalog includes every owned saved lead beyond one thousand entries',async()=>{await fixture();await call('bindings',{eventKeys:[]});const records=Array.from({length:1001},(_,i)=>({id:`large-${i}`,userId:'owner-a',email:`synthetic-${i}@example.test`,sourceType:'PEOPLE' as const,rawData:{}}));await db.lead.createMany({data:records});await db.leadListEntry.createMany({data:records.map(lead=>({id:`entry-${lead.id}`,listId:'list-a',leadId:lead.id}))});const response=await call('catalog');assert.equal(response.status,200);const catalog=await response.json();assert.equal(catalog.resources.entries.length,1002);assert.ok(catalog.resources.entries.some((entry:{id:string})=>entry.id==='entry-large-1000'));});
  await t.test('ownership requires both lead and list; foreign labels never export',async()=>{await fixture();await clear();await addLead('foreign-lead','foreign@example.test','owner-b','list-a');await addLead('foreign-list','foreign-list@example.test','owner-a','list-b');await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-b'}});assert.equal((await rows()).length,0);const catalog=await(await call('catalog')).json();assert.deepEqual(catalog.scopes.map((r:{id:string})=>r.id),['list-a']);assert.deepEqual(catalog.resources.entries.map((r:{id:string})=>r.id),['entry-lead-a']);assert.deepEqual(catalog.resources.labels.map((r:{id:string})=>r.id),['label-a']);assert.equal((await call('catalog',{subject:'owner-a'})).status,403);assert.equal((await call('catalog',{scopeId:'list-b'})).status,403);});
  await t.test('missing or invalid email is not fabricated and archived lists never capture',async()=>{await fixture();await clear();await addLead('no-email',null);await addLead('invalid','invalid');await addLead('archived','old@example.test','owner-a','archived');assert.equal((await rows()).length,0);});
  await t.test('explicit [] means no events and event keys select real operations',async()=>{await fixture();await clear();await call('bindings',{eventKeys:[]});await addLead('none','none@example.test');assert.equal((await rows()).length,0);await call('bindings',{eventKeys:['lead_label_added']});await addLead('label-only','label@example.test');assert.equal((await rows()).length,0);await db.leadEntryLabel.create({data:{entryId:'entry-label-only',labelId:'label-a'}});assert.equal((await rows()).length,1);assert.equal((await call('bindings',{eventKeys:['email_sent']})).status,400);});
  await t.test('predicates require the current contact email and refuse ambiguous entries',async()=>{await fixture();assert.deepEqual(await(await call('conditions/evaluate',{operation:'lead_in_list',contact:{email:'other@example.test'},filters:{}})).json(),{matched:false});await addLead('same','prospect@example.test');assert.equal((await call('conditions/evaluate',{operation:'lead_in_list',contact:{email:'prospect@example.test'},filters:{}})).status,409);assert.deepEqual(await(await call('conditions/evaluate',{operation:'lead_in_list',contact:{email:'prospect@example.test'},filters:{entryId:'entry-lead-a'}})).json(),{matched:true});});
  await t.test('owned existing label action writes real assignment and suppresses immediate export',async()=>{await fixture();await clear();const response=await call('actions/execute',action());assert.equal(response.status,200);const result=await response.json();assert.equal(result.alreadyApplied,false);assert.ok(await db.leadEntryLabel.findUnique({where:{id:result.assignmentId}}));assert.equal((await rows()).length,0);assert.deepEqual(await(await call('conditions/evaluate',{operation:'lead_has_label',contact:{email:'prospect@example.test'},filters:{labelId:'label-a'}})).json(),{matched:true});});
  await t.test('existing assignment is a stable no-op receipt, concurrent retries never duplicate',async()=>{await fixture();const existing=await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-a'}});await clear();const results=await Promise.all([call('actions/execute',action()),call('actions/execute',action())]);assert.ok(results.every(r=>r.status===200));const data=await Promise.all(results.map(r=>r.json()));assert.equal(data[0].assignmentId,existing.id);assert.equal(data[1].assignmentId,existing.id);assert.equal(data[0].alreadyApplied,true);assert.equal((await rows()).length,0);assert.equal(await db.leadEntryLabel.count(),1);});
  await t.test('concurrent new action retries create one assignment; later manual labels still export',async()=>{await fixture();await clear();const results=await Promise.all([call('actions/execute',action()),call('actions/execute',action())]);assert.ok(results.every(r=>r.status===200));const data=await Promise.all(results.map(r=>r.json()));assert.equal(data[0].assignmentId,data[1].assignmentId);assert.equal(await db.leadEntryLabel.count(),1);assert.equal((await rows()).length,0);await db.customLabel.create({data:{id:'label-next',userId:'owner-a',name:'Manual next'}});await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-next'}});assert.equal((await rows()).length,1);});
  await t.test('removed/replaced replay target is never recreated',async()=>{await fixture();const result=await(await call('actions/execute',action())).json();await db.leadEntryLabel.delete({where:{id:result.assignmentId}});assert.equal((await call('actions/execute',action())).status,409);assert.equal(await db.leadEntryLabel.count(),0);await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-a'}});assert.equal((await call('actions/execute',action())).status,409);});
  await t.test('foreign label/entry/email and changed idempotency content cannot mutate',async()=>{await fixture();assert.equal((await call('actions/execute',action({config:{labelId:'label-b'}}))).status,404);assert.equal((await call('actions/execute',action({contact:{email:'other@example.test'}}))).status,404);assert.equal((await call('actions/execute',action({config:{labelId:'label-a',entryId:'foreign'}}))).status,404);assert.equal((await call('actions/execute',action())).status,200);assert.equal((await call('actions/execute',action({config:{labelId:'label-a',entryId:'entry-lead-a'}}))).status,409);});
  await t.test('receipt write failure rolls back label assignment',async()=>{await fixture();await pool.query("CREATE FUNCTION synthetic_fail_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic failure'; END; $$; CREATE TRIGGER synthetic_receipt BEFORE INSERT ON scaleplus_automation_actions FOR EACH ROW EXECUTE FUNCTION synthetic_fail_receipt()");try{assert.equal((await call('actions/execute',action())).status,503);assert.equal(await db.leadEntryLabel.count(),0);}finally{await pool.query('DROP TRIGGER synthetic_receipt ON scaleplus_automation_actions; DROP FUNCTION synthetic_fail_receipt()');}});
  for(const[label,sql]of [ ['list owner changed','UPDATE "LeadList" SET "userId"=\'owner-b\' WHERE id=\'list-a\''],['lead owner changed','UPDATE "Lead" SET "userId"=\'owner-b\' WHERE id=\'lead-a\''],['list archived','UPDATE "LeadList" SET status=\'ARCHIVED\' WHERE id=\'list-a\''],['email changed','UPDATE "Lead" SET email=\'changed@example.test\' WHERE id=\'lead-a\''],['subject changed','UPDATE "User" SET "keycloakSubId"=\'new-subject\' WHERE id=\'owner-a\''] ])await t.test(`${label} cancels queued events and prevents stale action replay`,async()=>{await fixture();await call('actions/execute',action());await pool.query(sql);await drainOutbox(pool);assert.equal(received.length,0);assert.ok((await rows())[0].failed_at);assert.notEqual((await call('actions/execute',action())).status,200);});
  await t.test('label deletion or transfer cancels queued label events',async()=>{for(const change of ['DELETE FROM "LeadEntryLabel"','UPDATE "CustomLabel" SET "userId"=\'owner-b\' WHERE id=\'label-a\'']){await fixture();await clear();await db.leadEntryLabel.create({data:{entryId:'entry-lead-a',labelId:'label-a'}});await pool.query(change);await drainOutbox(pool);assert.equal(received.length,0);}});
  await t.test('pause/replayed activation does not reenable subscriptions',async()=>{await fixture();const id=randomUUID();await call('bindings',{},id);await call('bindings',{active:false});assert.equal((await(await call('bindings',{},id)).json()).active,false);await drainOutbox(pool);assert.equal(received.length,0);});
  await t.test('no scrape, enrichment, email, AI or credit action is available',async()=>{await fixture();for(const operation of ['search','enrich_email','send_email','run_ai'])assert.equal((await call('actions/execute',action({operation}))).status,400);});
  await t.test('retry IDs stay stable and strict ACK rejects ambiguous success',async()=>{await fixture();code=500;await drainOutbox(pool);await pool.query('UPDATE scaleplus_automation_outbox SET next_attempt_at=now()');code=200;await drainOutbox(pool);assert.equal(received[0].eventId,received[1].eventId);for(const response of [{status:200,body:{}},{status:200,body:{data:{accepted:true,mapped:false}}},{status:409,body:{data:{accepted:true}}}]){await fixture();code=response.status;ack=response.body;await drainOutbox(pool);assert.equal((await rows())[0].delivered_at,null);}});
  await t.test('redirect rejected, retries bounded and disabled source does not dispatch',async()=>{await fixture();code=307;await drainOutbox(pool);assert.equal(redirects,0);await pool.query('UPDATE scaleplus_automation_outbox SET attempts=7,next_attempt_at=now()');code=500;await drainOutbox(pool);assert.ok((await rows())[0].failed_at);await fixture();process.env.SCALEPLUS_AUTOMATIONS_ENABLED='false';await drainOutbox(pool);assert.equal(received.length,0);assert.equal((await call('catalog')).status,503);process.env.SCALEPLUS_AUTOMATIONS_ENABLED='true';});
 }finally{server.closeAllConnections();server.close();await db.$disconnect();await pool.end();}
});
